### PR TITLE
Removed dependency on CTK

### PR DESCRIPTION
**Pull request by drouin-simon**
Now, we use the vtkEventQtSlotConnect class from vtk to connect vtkObject and QObject instead of the CTK mechanism.

### CODE REVIEW

**Comment by christiana** [comment]
I have now tested your fix, and ran into some issues:

A) Two of the three tests failed

```
[11:53:18 ~/dev/igsio/OpenIGTLinkIO_build]$ ctest
Test project /Users/christiana/dev/igsio/OpenIGTLinkIO_build
    Start 1: testClientServer
1/3 Test #1: testClientServer .................   Passed    0.02 sec
    Start 2: testReceiveImage
2/3 Test #2: testReceiveImage .................***Failed    2.03 sec
    Start 3: testSendReceiveCommand
3/3 Test #3: testSendReceiveCommand ...........***Failed    2.02 sec

33% tests passed, 2 tests failed out of 3

```

B) When opening the example app igtlioQtClient, when adding a new Connector, the Devices view is not updated properly.

Both tests and example works OK on master.

**Comment by drouin-simon** [comment]
Damn. I will fix it. 

Did you run the tests on all platforms or just OSX? I only tested Ubuntu before commiting.

**Comment by christiana** [comment]
I only tested on my (old) Mac, OSX El Capitan, Qt 4.8.7, and using the setup from the igsio readme.

**Comment by drouin-simon** [comment]
I only tested Qt5. Could this be a Qt4/5 issue? I'll look into this as soon as I have a moment.

**Comment by christiana** [comment]
Correction: I am using Qt 5.6.0.

**Comment by jbbakeng** [comment]
COMPILING:
Latest commit on the drouin-simon:master branch did not compile on my Mac OSX El Capitan with Qt 5.6.1.

In file included from /Users/jbake/dev/boston/OpenIGTLinkIO/OpenIGTLinkIO/Examples/qIgtlClient/main.cpp:6:
In file included from /Users/jbake/dev/boston/OpenIGTLinkIO/OpenIGTLinkIO/GUI/qIGTLIOLogicController.h:7:
/Users/jbake/dev/boston/OpenIGTLinkIO/OpenIGTLinkIO/GUI/qIGTLIOVtkConnectionMacro.h:4:10: fatal error: 'vtkEventQtSlotConnect.h' file not found
#include "vtkEventQtSlotConnect.h"

Found out that vtkGUISupportQt needs to be an required component in the igtlioQtClient.

working:
find_package(VTK
  COMPONENTS
  vtkIOImage
  vtkImagingMath
  vtkGUISupportQt
  REQUIRED
  NO_MODULE)

not working:
find_package(VTK
  COMPONENTS
  vtkIOImage
  vtkImagingMath
  REQUIRED
  NO_MODULE)

CTEST:
When I added that line it compiled and I ran ctest which passed.

RUNNING:
This error which Christian reported is still there:
"B) When opening the example app igtlioQtClient, when adding a new Connector, the Devices view is not updated properly."

When I add more than one connector I get this output:
 ./bin/igtlioQtClient 
WARNING in: int qIGTLIOConnectorModel::rowCount(const QModelIndex& parent) const: Logic is a NULL object! Returning 0.
WARNING in: int qIGTLIOConnectorModel::rowCount(const QModelIndex& parent) const: Logic is a NULL object! Returning 0.
WARNING in: int qIGTLIODevicesModel::rowCount(const QModelIndex& parent) const: node is a NULL object! Returning 0.
WARNING in: int qIGTLIODevicesModel::rowCount(const QModelIndex& parent) const: node is a NULL object! Returning 0.

**Comment by drouin-simon** [comment]
I added the fix for vtkGUISupportQt. It makes sense. 

What puzzles me is why mine compiled? I assumed it did because other CMakeLists.txt in the tree already had the vtkGUISupportQt requirement. Could it be that we use different CMake generators?  I'm using CMake 3.7.1 on macOS 10.12 and the Unix Makefiles generator. I build either on the terminal or in QtCreator 4.1. 

I get the warnings you mentioned at startup. I will investigate this and the update problem.

**Comment by drouin-simon** [comment]
Warnings are unrelated to the changes I've made. I just need to check with the previous version, but I'm almost 100% sure these warnings where there before. The construction of the window produces calls to rowCount() on the classes derived from QAbstractItemModel before the pointer to Logic is set in them which causes the warning. Not sure the warning code should be there at all.

**Comment by drouin-simon** [comment]
Example window is now updating properly on OSX now.  The new reconnect function based on vtkEventQtSlotConnect was not handling reconnection properly when former target was 0.

**Comment by jbbakeng** [comment]
No idea why it worked for you and not for me. Maybe there is some caching issue? Did you try to remove cmake cache to try to reproduce the error? 

I use CMake 3.6.1 and the Eclipse CDT4 - Ninja generator. I build either in the terminal using ninja or in QtCreator 3.4.82 (QtC 4++ is not too happy when I use ninja so I have not upgraded).

Anyway the latest commit fixed the issues I mentioned so I am happy for now. :)
